/*
	Javascript Utils V2.1
	Author: Xerxis Anthony B. Alvar (Script Block)
	Application Utilities
	Dependencies : jQuery
*/
if(!window.APP)var APP=function(b){return{module:function(a,b){if("string"==typeof a&&"object"==typeof b){this[a]={};for(var d in b)this[a][d]=b[d]}else console&&("string"!=typeof a&&console.log("Module name is not a string"),"object"!=typeof b&&console.log("Module property is not an object"))},attrib:function(a,e){if("string"==typeof a&&"object"==typeof e)for(var d in this)d==a&&b.extend(this[a],e)},newmethod:function(a){for(var e in this)b.extend(this,a)}}}(jQuery);
APP.newmethod({preloadimages:function(){if(arguments.length)for(var b=0;b<arguments.length;b++)$("<img>").attr("src",arguments[b])},checkNumber:function(b){return/^[0-9]+$/.test(b)},checkEmail:function(b){return/^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/.test(b)},checkInput:function(b){return-1!=(""+b).search(/\S/)},checkCheckbox:function(b){return $(b).prop("checked")?1:0},checkSelect:function(b){return $(b).prop("selected")?1:0},isSgNric:function(b){var a=/^(S|T)\d{7}(A|B|C|D|E|F|G|H|I|Z|J)$/,
e=!0;if(b&&""!=b)if(a.test(b)){var d=b.toUpperCase(),b=d.substring(0,1),a=0;"T"==b&&(a+=4);var c=Number(d.substring(1,2)),f=Number(d.substring(2,3)),g=Number(d.substring(3,4)),h=Number(d.substring(4,5)),i=Number(d.substring(5,6)),j=Number(d.substring(6,7)),k=Number(d.substring(7,8)),d=d.substring(8,9),a=a+2*c,a=a+7*f,a=a+6*g,a=a+5*h,a=a+4*i,a=a+3*j,c="",a=(a+2*k)%11;if("S"==b||"T"==b)0==a&&(c="J"),1==a&&(c="Z"),2==a&&(c="I"),3==a&&(c="H"),4==a&&(c="G"),5==a&&(c="F"),6==a&&(c="E"),7==a&&(c="D"),8==
a&&(c="C"),9==a&&(c="B"),10==a&&(c="A");""!=c&&""!=d&&c!=d&&(e=!1)}else e=!1;return!e?!1:!0},isSgFin:function(b){var a=/^(F|G)\d{7}(K|L|M|N|P|Q|R|T|U|W|X)$/,e=!0;if(b&&""!=b)if(a.test(b)){var d=b.toUpperCase(),b=d.substring(0,1),a=0;"G"==b&&(a+=4);var c=Number(d.substring(1,2)),f=Number(d.substring(2,3)),g=Number(d.substring(3,4)),h=Number(d.substring(4,5)),i=Number(d.substring(5,6)),j=Number(d.substring(6,7)),k=Number(d.substring(7,8)),d=d.substring(8,9),a=a+2*c,a=a+7*f,a=a+6*g,a=a+5*h,a=a+4*i,a=
a+3*j,c="",a=(a+2*k)%11;if("F"==b||"G"==b)0==a&&(c="X"),1==a&&(c="W"),2==a&&(c="U"),3==a&&(c="T"),4==a&&(c="R"),5==a&&(c="Q"),6==a&&(c="P"),7==a&&(c="N"),8==a&&(c="M"),9==a&&(c="L"),10==a&&(c="K");""!=c&&""!=d&&c!=d&&(e=!1)}else e=!1;return!e?!1:!0},ValidateNRICFIN:function(b){b=b.toUpperCase();return!this.isSgNric(b)&&!this.isSgFin(b)?!1:!0}});